# Generated by Django 3.2.18 on 2023-03-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='title',
            field=models.CharField(default='Set your text here', max_length=100),
            preserve_default=False,
        ),
    ]
