# Generated by Django 3.2.18 on 2023-03-18 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20230318_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='type',
            field=models.CharField(choices=[('Records', 'Records'), ('Clothing', 'Clothing'), ('Posters', 'Posters'), ('Miscellaneous', 'Miscellaneous')], default='Records', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='year_item',
            field=models.IntegerField(default=2005, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
            preserve_default=False,
        ),
    ]
